/*
 * Copyright (C) 2015 Phil
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cnmstudio;

import clib.filter.CNMFilter;
import clib.layer.PageLayer;
import clib.layer.TextLayer;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Phil
 */
public class MainFrame extends javax.swing.JFrame {

    private final DefaultComboBoxModel comboLangModel = new DefaultComboBoxModel();
    private final PageReader pr = new PageReader();
    private PageCreator pc;
    private static boolean isStudio = true;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        init();
    }
    
    private void init(){
        try {
            javax.swing.UIManager.setLookAndFeel(new NimbusLookAndFeel());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException exc) {
            System.out.println("Nimbus LookAndFeel not loaded : "+exc);
        }
        
        //-- dim >> Obtient la taille de l'écran
        //-- gconf >> Obtient la configuration de l'écran
        //-- insets >> Obtient les 'marges' de l'écran
        java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Dimension dim = toolkit.getScreenSize();
        java.awt.GraphicsConfiguration gconf = java.awt.GraphicsEnvironment
                .getLocalGraphicsEnvironment().getDefaultScreenDevice()
                .getDefaultConfiguration();
        java.awt.Insets insets = toolkit.getScreenInsets(gconf);
        setSize(dim.width - insets.left - insets.right,
                dim.height - insets.top - insets.bottom);
        
        comboLanguage.setModel(comboLangModel);
        comboLanguage.setPreferredSize(new Dimension(350, comboLanguage.getHeight()));
        
        jDesktopPane1.add(pr);
        pr.setVisible(true);
        
        pc = new PageCreator(this);
        StudioPanel.add(pc);
    }
    
    private void searchForLanguage(){
        comboLangModel.removeAllElements();
        for(PageLayer pl : pr.getPage().getPages()){
            for(TextLayer tl : pl.getTexts()){
                Set<TextLayer.ISO_3166> set = tl.getTextCountries();                
                for (TextLayer.ISO_3166 country : set) {
                    if(comboLangModel.getIndexOf(country) < 0){
                        comboLangModel.addElement(country);
                    }
                }
            }
        }
    }
    
    private void changeLanguage(){
        for(PageLayer pl : pr.getPage().getPages()){
            for(TextLayer tl : pl.getTexts()){
                tl.setCountry((TextLayer.ISO_3166)comboLanguage.getSelectedItem());
                pr.viewCurrent();
            }
        }
    }
    
    public static boolean isStudio(){
        return isStudio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcXML = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        StudioPanel = new javax.swing.JPanel();
        PlayerPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnOpenDocument = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboLanguage = new javax.swing.JComboBox();
        btnPreviousPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comics'n'Mangas Studio");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        StudioPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Studio", StudioPanel);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnOpenDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clib/images/folder20.png"))); // NOI18N
        btnOpenDocument.setToolTipText("Open a document...");
        btnOpenDocument.setFocusable(false);
        btnOpenDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDocument.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpenDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDocumentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpenDocument);

        jLabel1.setText("Language : ");
        jToolBar1.add(jLabel1);

        comboLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLanguageItemStateChanged(evt);
            }
        });
        jToolBar1.add(comboLanguage);

        btnPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clib/images/20px-Crystal_Clear_action_back.png"))); // NOI18N
        btnPreviousPage.setToolTipText("Go to previous page");
        btnPreviousPage.setFocusable(false);
        btnPreviousPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreviousPage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPreviousPage);

        btnNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clib/images/20px-Crystal_Clear_action_forward.png"))); // NOI18N
        btnNextPage.setToolTipText("Go to next page");
        btnNextPage.setFocusable(false);
        btnNextPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNextPage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNextPage);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PlayerPanelLayout = new javax.swing.GroupLayout(PlayerPanel);
        PlayerPanel.setLayout(PlayerPanelLayout);
        PlayerPanelLayout.setHorizontalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        PlayerPanelLayout.setVerticalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        jTabbedPane1.addTab("Reader", PlayerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDocumentActionPerformed
        for (FileFilter f : fcXML.getChoosableFileFilters()){
            fcXML.removeChoosableFileFilter(f);
        }
        fcXML.setDialogTitle("Open the document...");
        fcXML.setDialogType(JFileChooser.OPEN_DIALOG);
        fcXML.setFileFilter(new CNMFilter());
        int z = fcXML.showOpenDialog(this);
        if (z == JFileChooser.APPROVE_OPTION){
            try {
                Reader r = new Reader();
                File f = new File(System.getProperty("user.home") + File.separator + ".cnmFiles");
                if(f.exists()==false){
                    f.mkdir();
                }                
                pr.setPage(r.readCNM(fcXML.getSelectedFile().getAbsolutePath(), System.getProperty("user.home") + File.separator + ".cnmFiles" + File.separator));
//                Reader reader = new Reader(fcXML.getSelectedFile().getAbsolutePath());
//                pr.setPage(reader.getPage());
                pr.viewCurrent();
                searchForLanguage();
            } catch (ParserConfigurationException | SAXException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenDocumentActionPerformed

    private void comboLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLanguageItemStateChanged
        try{
            changeLanguage();
        }catch(Exception ex){

        }
    }//GEN-LAST:event_comboLanguageItemStateChanged

    private void btnPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPageActionPerformed
        try{
            pr.viewPrevious();
        }catch(Exception ex){

        }
    }//GEN-LAST:event_btnPreviousPageActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        try{
            pr.viewNext();
        }catch(Exception ex){

        }
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        isStudio = jTabbedPane1.getSelectedIndex() == 0;
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlayerPanel;
    private javax.swing.JPanel StudioPanel;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnOpenDocument;
    private javax.swing.JButton btnPreviousPage;
    private javax.swing.JComboBox comboLanguage;
    private javax.swing.JFileChooser fcXML;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
