/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnmstudio;

import clib.io.Page;
import clib.layer.PageLayer;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Yves
 */
public class PageReader extends javax.swing.JInternalFrame {

        private final JScrollPane editorScrollPane = new JScrollPane();
        private Page page = new Page();
        private int currentIndex = 0;
    
    /**
     * Creates new form PageReader
     */
    public PageReader() {
        initComponents();
        init();
    }
    
    private void init(){
        try {
            javax.swing.UIManager.setLookAndFeel(new NimbusLookAndFeel());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException exc) {
            System.out.println("Nimbus LookAndFeel not loaded : "+exc);
        }
        
        editorPanel.add(editorScrollPane);
        editorScrollPane.setVisible(false);
    }
    
    public void setPage(Page page){
        this.page = page;
    }
    
    public Page getPage(){
        return page;
    }
    
    public void viewPrevious(){
        currentIndex -= 1;
        if(currentIndex < 0){
            currentIndex = 0;
        }
        PageLayer pl = page.getPages().get(currentIndex);
        page.setActualPage(pl);
        updateImage(pl);
        page.repaint();
    }
    
    public void viewNext(){
        currentIndex += 1;
        if(currentIndex > page.getPages().size()-1){
            currentIndex = page.getPages().size()-1;
        }
        PageLayer pl = page.getPages().get(currentIndex);
        page.setActualPage(pl);
        updateImage(pl);
        page.repaint();
    }
    
    public void viewCurrent(){
        if(currentIndex > page.getPages().size() | currentIndex < 0){
            currentIndex = 0;
        }
        PageLayer pl = page.getPages().get(currentIndex);
        page.setActualPage(pl);
        updateImage(pl);
        page.repaint();
    }
    
    private void updateImage(PageLayer pl){
        page.setSize(pl.getWidth(), pl.getHeight());
        page.setPreferredSize(new Dimension(pl.getWidth(), pl.getHeight()));
        
        editorScrollPane.setSize(
                pl.getWidth()+20 > editorPanel.getWidth() ? editorPanel.getWidth() : pl.getWidth()+20, 
                pl.getHeight()+20> editorPanel.getHeight()? editorPanel.getHeight(): pl.getHeight()+20);
        
        editorScrollPane.setLocation( (editorPanel.getWidth() - editorScrollPane.getWidth())/2, 0);
        
        editorScrollPane.setViewportView(page);
        editorScrollPane.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorPanel = new javax.swing.JPanel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        editorPanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        try{
            viewCurrent();
        }catch(Exception ex){
            //C'est normal qu'on plante au début du programme :P
        }        
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editorPanel;
    // End of variables declaration//GEN-END:variables
}
